name: "Analyze"
on:
  workflow_dispatch:
  push:

jobs:
  Analyze:
    runs-on: eclairit-1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Analyze
      run: |
        cd ECLAIR
        # Prepare for build
        ../prepare.sh Debug
        # Analyze the project
        ./analyze.sh
        # Make the directory for ECLAIR project database
        mkdir -p ~/github/$GITHUB_REPOSITORY/$GITHUB_RUN_NUMBER && rm -f ~/github/$GITHUB_REPOSITORY/last_$GITHUB_REF_NAME && ln -s ~/github/$GITHUB_REPOSITORY/$GITHUB_RUN_NUMBER ~/github/$GITHUB_REPOSITORY/last_$GITHUB_REF_NAME
        # Copy the project database
        scp out/PROJECT.ecd ~/github/$GITHUB_REPOSITORY/$GITHUB_RUN_NUMBER
        # Publish ECLAIR report link
        echo "https://eclairit.com:3787/fs/home/emelin/github/$GITHUB_REPOSITORY/$GITHUB_RUN_NUMBER/PROJECT.ecd"
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ECLAIR/out


    - name: reports SARIF
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ECLAIR/gh-quality-report.sarif
      
